### ISSUE TITLE
Battery Level

### ISSUE THREAD

**Issue by romanbuehlervowa** [Octanis3/Octanis3-Data#3]
We checked two systems yesterday and concerning battery level we were at 5.2 and 4.8 after one month of running. At what level of Voltage do we need to be concerned and have to change battery? To be sure I exchanged the one with 4.8

**Comment by traffael** [comment]
Thanks for pointing out that the information was missing on the wiki. 
Added it on the page on power management: https://wiki.octanis.org/octanisx/nestbox/power#battery_change

Also added issue https://github.com/Octanis3/website/issues/1 for the control center
