### ISSUE TITLE
Visualizer bugs when IDs 00000000 existent in files

### ISSUE THREAD

**Issue by romanbuehlervowa** [Octanis3/Octanis3-Data#4]
When there are "ghost" IDs (such as 000000000 or 0000F0000.....)detected and they are in the log files the visualizer doesn't visualize the weights properly

**Comment by traffael** [comment]
Could you list a few example log repositories where this happens?

**Comment by traffael** [comment]
000000000 and similar ID's aren't responsible for the error. 

Potential cause: long gaps within the log files --> has been ruled out as well.

**Comment by NathanGelle** [comment]
![image](https://user-images.githubusercontent.com/50208089/65515749-0b970d00-dee0-11e9-9a53-6111c457ec49.png)

Example: Champmartin - log files from 2 to 1796

**Comment by traffael** [comment]
Could confirm same error with files LOG510 to LOG01796 (Champmartin deact/17.04.19)

**Comment by NathanGelle** [comment]
![image](https://user-images.githubusercontent.com/50208089/65516327-1e5e1180-dee1-11e9-8592-a45b123d636a.png)

Fruchtsur : log files 1 to 1000

**Comment by traffael** [comment]
Identified file which produces the error:
[LOG01740.TXT](https://github.com/Octanis3/Octanis3-Data/files/3647467/LOG01740.TXT)

Note this is a file generated in the evening after going to standby during the day. It directly has a (false) detection and starts logging weight values. Potentially, this means that a long period without offset measurements is before it.

**Comment by traffael** [comment]
For previous file, it is enough to add some "fake" offset lines before the X lines in order for the visualizer to work again.

[LOG01740_modified.TXT](https://github.com/Octanis3/Octanis3-Data/files/3647501/LOG01740_modified.TXT)

**Comment by NathanGelle** [comment]
[LOG00909.TXT](https://github.com/Octanis3/Octanis3-Data/files/3647537/LOG00909.TXT)
[LOG00909bis.TXT](https://github.com/Octanis3/Octanis3-Data/files/3647538/LOG00909bis.TXT)

Example of Fruchtsur : log files 909 with no "O" doesn't work, but log files 909bis with fake "O" works

**Comment by NathanGelle** [comment]
[LOG00510.TXT](https://github.com/Octanis3/Octanis3-Data/files/3647554/LOG00510.TXT)
[LOG00510bis.TXT](https://github.com/Octanis3/Octanis3-Data/files/3647555/LOG00510bis.TXT)

Example of Fruchtsur : log files 510 with no "O" doesn't work, but log files 510bis with fake "O" works

**Comment by traffael** [comment]
Important info: the offset lines must have  a timestamp that is smaller than the R line

**Comment by traffael** [comment]
Easy fix: if no offset can be calculated from "O" log lines, simply use the value of the "H" line, which is present in each file.

**Comment by lpatiny** [comment]
Should be fixed.
